name: admin_panel
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  dynamic_height_grid_view: ^0.0.3
  fancy_shimmer_image: ^2.0.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  fluttertoast: ^8.2.4
  image_picker: ^0.8.7+5
  ionicons: ^0.2.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/dashboard/
